# Generated by Django 4.0.3 on 2022-06-08 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Tipo',
            },
        ),
        migrations.CreateModel(
            name='Verif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf_cnpj', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Verificação',
            },
        ),
    ]
